name: quicksend
description: A secure, private instant messaging service
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  dio: ^4.0.6
  web_socket_channel: ^2.2.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2
  fast_rsa: ^3.4.7
  uuid: ^3.0.6
  encrypt: ^5.0.1
  archive: ^3.3.0
  intl: ^0.17.0
  loading_animation_widget: 1.2.0+1
  skeletons: ^0.0.3
  image_picker_web: ^2.1.1
  mime_type: ^1.0.0
  path: ^1.8.1
  image_picker: ^0.8.5+3
  device_info_plus: ^3.2.4
  easy_image_viewer: ^1.0.4
  image_editor_plus: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.2

flutter_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/img/icon.png"

flutter_native_splash:
  color: "#0e0f19"
  image: assets/img/icon-transparent.png
  android_12:
    color: "#0e0f19"
    image: assets/img/icon-transparent.png

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - packages/fast_rsa/web/assets/worker.js
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand-regular.ttf
          weight: 400
        - asset: assets/fonts/quicksand-medium.ttf
          weight: 500
        - asset: assets/fonts/quicksand-bold.ttf
          weight: 700
        - asset: assets/fonts/quicksand-light.ttf
          weight: 300
